version: "3"
services:
  ba-identity:
    build: ./ba-identity
    ports:
      - "5011:8080"
    volumes:
      - /C/Users/Vadim/Documents/db:/usr/db
  ba-api:
    build: ./ba-api
    ports:
      - "5010:8080"
    volumes:
      - /C/Users/Vadim/Documents/db:/usr/db
  ba-web:
    build:
      context: ./ba-web
      args:
        - REACT_APP_IDENTITY_URL=http://budgetsapp.com:5011
        - REACT_APP_BASE_URL=http://budgetsapp.com:5010/graphql
    ports:
      - "80:80"
